// This is just some sample data so you don't have to think of your own!
module.exports = {
  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish6: {
    clientName: 'Atlantic Salmon',
    clientPhone: 'http://i.istockimg.com/file_thumbview_approve/56241842/5/stock-photo-56241842-salmon-fish.jpg',
    deliveryDate: 'This flaky, oily salmon is truly the king of the sea. Bake it, grill it, broil it...as good as it gets!',
    deliveryHour: 1453,
    shippingAddress: 'available',
    shippingPrice: 'available',
    shippingInCharge: 'available',
    status: true,
    payment1: 2000,
    payment2: 2000,
    balance: 0,
    total: 0,
  },

  fish9: {
    name: 'Jumbo Prawns',
    image: 'http://i.istockimg.com/file_thumbview_approve/67121439/5/stock-photo-67121439-fresh-tiger-shrimp-on-ice-on-a-black-stone-table.jpg',
    desc: 'With 21-25 two bite prawns in each pound, these sweet morsels are perfect for shish-kabobs.',
    price: 2250,
    status: 'available'
  }
};
